### ISSUE TITLE
Kommentarer Peer-Review 1

### ISSUE THREAD

**Issue by ej222pj** [rk222ev/1dv450-Registering-rk222ev#1]
Kan inte klaga på något! Jag tycker du har skrivit snygg kod och det känns som att du kan Ruby sen innan. Det känns välgjort när jag kollar igenom koden.   
Jag har inte hittat några buggar när jag testkört och all funktionalitet fungerar som den ska.

Jag märkte att du använde ett gem som heter "slim" för dina vyer, det tog lite tid för mig att förstå hur det fungerade men när jag kollat på det verkar det som ett bra sätt att skriva vyer på.   

Snyggt gjort att det gick att editera en inloggad användare med "/users/edit" men det saknades en länk dit. (Fast det var ju inget krav för första uppgiften)   

Jag hade gärna haft mer utförliga instruktion om hur man startar applikationen, för att jag programmerade i Cloud9 och visste därför inte hur jag startar det med vagrant. Men jag körde igång din applikation på Cloud9 så det var inga problem.

**Comment by rk222ev** [comment]
Hej!

Tack för din review.
Som du säger är jag bekant med ruby sedan tidigare.

Härligt att allt fungerar även för dig. Är alltid lite spännande när någon annan testar.

Jag gillar verkligen slim. Blir så lite noise som stör och underlättar verkligen läsbarheten när man kommit in i syntaxen.

Ah, tänkte fixa edit grejern, men fick lite tidsbrist så blev inte färdigt.
Dock skulle den delen egentligen vara låst... Jag får åtgärda det.
Håller issuen öppen tills jag fixat klart edit vyn.

Har tyvärr tittat väldigt lite på Cloud9 så är tyvärr inte så insatt i hur den miljön fungerar. Instruktionerna var skrivna med OS X som utgångspunkt. Men att ge exempel på att köra igång i cloud9 är ju smart då blir det plattformsoberoende och väldigt lätt att komma igång.

Ha det gott!

**Comment by rk222ev** [comment]
Nu finns det en länk till editering av sina användaruppgifter.
Passade även på att förbättra layouten på editeringssidan och eventuella felmeddelande.

Se commit: 1558168e543e8691e169270e47942a29166427e8

Stänger issuen!

**Comment by 1dv450** [comment]
Bra!
