### ISSUE TITLE
Inloggnigen

### ISSUE THREAD

**Issue by mc22ft** [rk222ev/1dv450-Registering-rk222ev#2]
Lite förvirrad här?

1. Som API användare ska det hämta ut "read only" från API:et med hjälp av en api nyckel. Jag hittar ingen API nyckel i något anrop. 

2. Användaren/skapare av event ska "Logga in och lägga till, uppdatera och ta bort sina egna händelser/platsbeskrivningar dvs alla "un-safe" methods i ditt API". Hittar inte någon anrop där jag kan logga in med en användare(username och password).

Du använder JWT för inloggningen och skickar ett bearer med varje anrop. Och matchar detta mot en användare. Din inloggning är för en API användare(nr 7). Vad jag har förstått med JWT är att du skickar in en användare och får tillbaka en token som du använder i anrop mot API:et. Efter ett tag så går detta token ut och du måste hämta ett nytt. Det bearer token du har skulle kunnas kopieras och användas som en "vanlig" nyckel.

Din users tabell i databasen är användare för både API användare och skapare av event. Det är inte "samma" användare och skulle separera detta och skapat en creator tabell för event skaparen.

Blev några saker men jag tycker allt hänger ihop. 

En notis: Inloggning med admin i registreringsapplikation verkar omdirigera fel.

**Comment by rk222ev** [comment]
## 1.
 Api nyckeln kommer i payload här:
https://github.com/rk222ev/1dv450-Registering-rk222ev/blob/master/app/services/jwt_service.rb#L15
och kontrolleras mot databasen här:
https://github.com/rk222ev/1dv450-Registering-rk222ev/blob/master/app/controllers/api/base_controller.rb#L11

När man decodat jwt token ser den ut på följande sätt när frontend har skickat med en användare 

```shell
{
  "iss": "LIdQwOIWeho1nOeb1ouRb1oro13LflEjg",
  "email": "api_user@example.com",
  "password": "password"
}
```

Iss är då token. 


## 2

Se 1.

## Övrigt 
Min token är encodad i JWT så och måste ha en giltig secret för att kunna  läsas upp. Men mycket möjligt att jag misstolkat JWT då jag inte lagt mycket tid på det. Men encodar man inte sin payload med en secret som bara klienten och servern känner till och decodar denna. För att man just inte ska kunna läsa ut informationen som skickas mellan klient och server? Absolut skulle nyckeln kunna kopieras, men då kommer man inte åt api nyckeln eller användarens uppgifter utan att känna rätt secret.

Har du ett bra exempel så får du gärna länka då jag som sagt inte satt mig in i frågan särskilt mycket utan bara antog att apinyckel och användaruppgifter skulle delas säkert mellan klient och server encodat i en JWT med en delad secret. För att man inte ska läcka användaruppgifter när kommunikationen skickas. Då REST är stateless trodde jag detta var det korrekta arbetssättet.

En användare är en användare. Men skulle egentligen normaliserat databasen ett steg till och lyft ur api key då inte alla användare kommer att ha api nycklar.
Att skapa en identiskt databas som innehåller samma uppgifter tycker jag bryter mot databas normalisering för mycket och jag vill inte föra dubbla tabeller. Då en användare som har en nyckel också skulle kunna vilja använda apit.

Ah, får kika på redirecten där!

Återkommer med en separat issue.

Hinner du får du gärna utveckla JWT och hur det ska fungera!

**Comment by mc22ft** [comment]
1. Jag är lite osäker på hur du menar. Jag är inte någon super star i JWT :)

2. Hur skulle en användare logga in som inte har en API nyckel? 

Ang databasen. Jag ser det som två olika användare som inte borde blandas ihop. Men du ser ju på det på ett annat sätt och har argument för det. Det är ok för mig. Gillar att du har en inloggning counter i db:en.

MEN, jag skulle föreslå att vi vänder oss till John eller någon som har koll på JWT som kan förklara hur det ska vara? Så blir det rätt från början utan att spilla massa tid och grubbel? Jag menar att jag vill ju veta hur det ska fungera till 100% också. Eller vad tycker du?

**Comment by rk222ev** [comment]
1. Nej verkligen inte jag heller. Har lagt lite för lite tid på JWT biten. Hade hoppats på att du kunde skjuta ner min teori och visa rätt sätt!

2. Nyckeln tillhör klient appen. Sen skickar appen med en användare som i sin tur använder klienten. Så vill man påverkar information i applikationen måste uppgifterna skickas med i sin request.

Men nu ser jag problemet. Nu förstår jag hur du menar. Du vill kunna logga in en gång mot tjänsten och sedan ha en token utan att behöva skicka autentiseringsuppgifter igen. Så har jag inte tänkt. Tänkte att man får snällt autentisera sig varje request. Sen inser jag nu att det saknas en endpoint för att kontrollera att användaruppgifterna är korrekta för att tillåta klienten att autentisera en användares uppgifter.

Men ja, ser man tjänsten så. Så går det inte i dagsläget. Är nog jag som inte funderat tillräckligt över hur tjänsten ska fungera. Minns bara att John sa att man ska skicka autentiseringuppgifter vid varje request och sedan jag har liksom inte funderat på det utan bara tagit rad för rad och implementerat requesten utan att egentligen reflektera över hur det ska användas tillsammans med klienten. 

Höra med John låter som en bra idé. Men misstänker att det är jag som misstolkat då jag helt enkelt kollat väldigt flyktigt på JWT.

**Comment by rk222ev** [comment]
Forskade lite på JWT. 
Du har rätt. Jag har missuppfattat hur JWT ska användas(Inte läst klart deras introduction).
Åtgärdar.

**Comment by mc22ft** [comment]
Vad skönt att det löste sig för dig/oss. 

Kan tipsa om att titta på Johns exempel kod på github. Ligger lite typ lite gömd i helpers:
https://github.com/thajo/1dv450_demo/blob/master/app/helpers/sessions_helper.rb

**Comment by rk222ev** [comment]
[Denna commit](https://github.com/rk222ev/1dv450-Registering-rk222ev/commit/636d64b83d59c5aaa3511cb51a1c7b5d6b370ba7) borde lösa problemet med JWT. 

Tack för utpekad riktning och sparken i baken!
