### ISSUE TITLE
Kommentarer

### ISSUE THREAD

**Issue by mc22ft** [rk222ev/1dv450-Registering-rk222ev#3]
Koden är mycket bra och förstående men saknar helt kommentarer vid funktioner som skulle behöva en. Bland annat i din base_controller finns check_for_api_key skulle det varit bra med en kommentar för att snabbt förstå vad den gör/är till för.

**Comment by rk222ev** [comment]
Kan hålla med om att namnet på just check_for_api_key inte är klockrent.
Skulle nog bytt till en method som heter parse_jwt som i sin tur använder check_for_api_key och authenticate_user för att klargöra vad metoden gör på ett lite bättre sätt.
Då tycker jag att en kommentar blir överflödig då de tre rader metoden skulle innehålla i stort sätt skulle vara samma text som min kommentar hade bestått av.

Då funktionerna är väldigt korta och namnet oftast beskriver precis vad som händer hade kommentarer blivit en upprepning av funktionsnamnet. Något jag inte tycker medför något värde och därför inte kom in i koden.

Har du några bra konkreta exempel får du gärna visa då jag är extremt dålig på att skriva meningsfulla kommentarer och tar gärna emot förslag på bra kommentarer så kanske jag kan lära mig!

**Comment by mc22ft** [comment]
Det var just på den funktionen som jag inte förstod vad den gjorde och antagligen på grund av tidigare funderingar kring issue 2. Men jag tycker det ser bra ut nu när jag har tittat en del på din kod.

Inget mer att tilläga på denna issue.

**Comment by rk222ev** [comment]
Ok, Vet att jag är extremt dålig på att skriva kommentarer. Så bra issue med dålig undanflykt från mig.. Men blev lite bättre med [denna commit](https://github.com/rk222ev/1dv450-Registering-rk222ev/blob/0a708e91095cc7f782b88b1c8d189436a3dd0f98/app/controllers/api/base_controller.rb)

Men tar till mig av issuen och ska försöka tänka på mina kommentarer!
